#!/usr/bin/env python3
"""FM1 medical-metric eligibility and metric-endpoint independence audit."""

from __future__ import annotations

import csv
import hashlib
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[4]
PACKAGE_DATA = ROOT / "infrastructure/packages/vlm_pathology_metrics/src/vlm_pathology_metrics/data"
OUT = Path(__file__).resolve().parent / "outputs"
OUT.mkdir(parents=True, exist_ok=True)
MEDICAL_FILES = tuple(sorted((PACKAGE_DATA / "medical").glob("tier*.tsv")))
ANALYSIS_FILE = PACKAGE_DATA / "analysis/analysis_measure_catalog.tsv"
PLAN = ROOT / "projects/quantitative_foundation_model_validation/docs/research_plan/14_FOUNDATION_MODEL_QUANTITATIVE_METRIC_VALIDATION_PLAN_KO.md"
PROTOCOL = ROOT / "projects/quantitative_foundation_model_validation/preexperiment/PROTOCOL.md"
SEED = 20260811


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def write_delimited(path: Path, fields: Iterable[str], rows: Iterable[dict[str, object]], delimiter: str) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fields), delimiter=delimiter, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def audit_medical(row: dict[str, str]) -> dict[str, object]:
    metric_id, tier, status = row["metric_id"], row["tier"], row["status"]
    if tier == "T4":
        independence = "model_dependent_not_independent_truth"
        readiness = "available_model_output_not_reference_measurement" if status == "active" else "deferred_model_output"
        h1 = "prohibited_as_independent_concept_target"
        allowed = "model_output_or_candidate_triage_only"
        h2 = "prohibited_as_independent_metric"
        block = "metric is generated by a model or frozen model transform"
    elif row["domain"] == "clinical_outcome":
        independence = "independent_clinical_outcome_if_source_verified"
        readiness = "catalog_active_cohort_linkage_not_yet_audited" if status == "active" else "deferred"
        h1 = "excluded_from_H1_metric_target_endpoint_only"
        allowed = "disease_endpoint_only"
        h2 = "eligible_as_Y_not_as_M_after_provenance_and_linkage"
        block = "subject linkage, event definition, censoring, treatment and external cohort not audited"
    elif tier == "T1":
        independence = "clinician_or_assay_reference_independent_of_encoder"
        if status == "active":
            readiness = "catalog_active_dataset_availability_requires_cohort_audit"
            h1 = "eligible_if_linked_truth_available"
            allowed = "candidate_metric_target_or_clinical_covariate"
            h2 = "candidate_requires_independent_endpoint_pair"
            block = "same-subject metric truth, measurement timing and independent endpoint not yet linked"
        else:
            readiness = "deferred_dataset_or_measurement_not_available"
            h1 = "deferred_until_truth_available"
            allowed = "planning_only"
            h2 = "deferred"
            block = "catalog marks measurement deferred"
    elif metric_id == "candidate.tumor_fraction":
        independence = "expert_annotation_derived_independent_of_encoder"
        readiness = "ready_for_descriptive_feasibility_repeatability_not_quantified"
        h1 = "eligible_descriptive_now"
        allowed = "descriptive_H1_only"
        h2 = "exploratory_only_missing_independent_Y_and_external_validation"
        block = "measurement repeatability and same-subject independent endpoint/external cohort absent"
    elif tier == "T2" and status == "exploratory":
        independence = "clinician_anchored_but_algorithm_or_method_dependent"
        readiness = "exploratory_measurement_validation_required"
        h1 = "exploratory_only"
        allowed = "method_development_only"
        h2 = "prohibited_until_measurement_validation"
        block = "repeatability or fixed validated derivation is absent"
    elif tier == "T2":
        independence = "clinician_anchored_derived_if_parents_and_method_locked"
        readiness = "deferred_measurement_or_parent_inputs"
        h1 = "deferred_until_measurement_ready"
        allowed = "planning_only"
        h2 = "deferred"
        block = "required parents, contour or validated derivation not available"
    else:
        independence = "encoder_independent_computational_proxy_if_algorithm_locked"
        readiness = "research_proxy_requires_method_and_transport_validation"
        h1 = "exploratory_only"
        allowed = "research_method_development"
        h2 = "prohibited_until_independent_validation"
        block = "computational proxy is not an independent clinical reference"
    return {
        **row,
        "registry_boundary": "medical_metric",
        "reference_independence": independence,
        "measurement_readiness": readiness,
        "h1_recoverability_status": h1,
        "allowed_fm_role": allowed,
        "h2_candidate_status": h2,
        "blocking_evidence": block,
        "decision_basis": "catalog tier/status/source_type plus FM1 prespecified rules; active does not imply cohort availability",
    }


def h2_pairs() -> list[dict[str, str]]:
    common = "same-subject M/Y linkage; measurement timing; subject/event adequacy; locked disease head; external validation"
    rows = [
        ("H2-001", "pathology.isup_grade_group", "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent", "noncircular", "priority_candidate_planning_only", "recurrence is not defined by ISUP grade", f"{common}; treatment covariates"),
        ("H2-002", "pathology.gleason_total_score", "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent", "noncircular", "secondary_candidate_redundant_with_ISUP", "recurrence is not defined by Gleason score; overlaps the primary grade family", f"{common}; multiplicity and redundancy rule"),
        ("H2-003", "pathology.cancer_extent_percent", "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent", "noncircular", "exploratory_planning_only", "recurrence label does not use cancer extent directly", common),
        ("H2-004", "candidate.tumor_fraction", "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent_in_definition_unlinked_in_data", "noncircular", "blocked_missing_linked_cohort", "tumor fraction does not define recurrence but PRECISE lacks the linked endpoint", f"{common}; repeatability evidence"),
        ("H2-005", "pathology.tumor_presence", "diagnosis.prostate_cancer", "circular", "endpoint_defined_by_metric", "prohibited", "tumor presence directly defines the diagnosis", "choose an endpoint not defined by tumor presence"),
        ("H2-006", "pathology.pni_presence", "diagnosis.pni", "circular", "endpoint_defined_by_metric", "prohibited", "PNI presence directly defines a PNI diagnosis", "use a separately defined clinical endpoint"),
        ("H2-007", "pathology.pni_presence", "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent_in_definition_unlinked_in_data", "noncircular", "blocked_selected_sample_and_no_outcome", "recurrence is independent of PNI definition, but the selected PRECISE review cannot support population inference", common),
    ]
    for index, metric in enumerate(("assay.pten_status", "assay.erg_status", "assay.spop_status", "assay.ar_activity"), 8):
        rows.append((f"H2-{index:03d}", metric, "outcome.biochemical_recurrence_status;outcome.biochemical_recurrence_free_time", "independent_if_assay_and_outcome_provenance_confirmed", "noncircular", "study_local_candidate_catalog_and_linkage_required", "molecular assay does not define recurrence", f"register assay as study-local T1 reference; {common}; site and purity audit"))
    fields = ("pair_id", "metric_id", "endpoint_id", "endpoint_independence", "circularity", "fm1_status", "rationale", "required_before_fm6")
    return [dict(zip(fields, row)) for row in rows]


def local_references() -> list[dict[str, str]]:
    return [
        {"metric_id": metric, "provisional_tier": "T1", "reference_type": reference, "fm1_status": "study_local_candidate_not_central_catalog", "allowed_role": "H1 target and H2 metric only after provenance audit", "required_action": action}
        for metric, reference, action in (
            ("assay.pten_status", "independent IHC/FISH/molecular assay", "lock loss definition, specimen, assay version, validator and site/purity audit"),
            ("assay.erg_status", "independent IHC or molecular assay", "lock positivity definition, specimen, assay version and validator"),
            ("assay.spop_status", "independent sequencing assay", "lock variant definition, sequencing pipeline, specimen and validator"),
            ("assay.ar_activity", "independent transcriptomic or assay-derived score", "lock gene set, normalization, score version, specimen and site audit"),
        )
    ]


def main() -> None:
    started = utc_now()
    medical_rows = [row for path in MEDICAL_FILES for row in read_tsv(path)]
    analysis_rows = read_tsv(ANALYSIS_FILE)
    if len(medical_rows) != 58 or len(analysis_rows) != 73:
        raise RuntimeError(f"catalog count mismatch: medical={len(medical_rows)}, analysis={len(analysis_rows)}")
    ids = [row["metric_id"] for row in medical_rows]
    if len(ids) != len(set(ids)):
        raise RuntimeError("duplicate medical metric_id")
    medical = [audit_medical(row) for row in medical_rows]
    medical_fields = list(medical[0])
    write_delimited(OUT / "medical_metric_eligibility.tsv", medical_fields, medical, "\t")
    boundary = [
        {
            **row,
            "registry_boundary": "analysis_measure_not_medical_metric",
            "eligible_as_independent_medical_target": "False",
            "eligible_as_patient_feature": "False",
            "allowed_role": "evaluation_QC_inference_or_audit_only",
            "boundary_reason": "performance/QC/statistical measures evaluate the study; they are not clinician-used patient quantities",
        }
        for row in analysis_rows
    ]
    write_delimited(OUT / "analysis_measure_boundary.tsv", list(boundary[0]), boundary, "\t")
    pairs = h2_pairs()
    write_delimited(OUT / "metric_endpoint_independence.tsv", list(pairs[0]), pairs, "\t")
    local = local_references()
    write_delimited(OUT / "study_local_reference_candidates.tsv", list(local[0]), local, "\t")

    tier_counts = Counter(row["tier"] for row in medical)
    h1_counts = Counter(str(row["h1_recoverability_status"]) for row in medical)
    h2_counts = Counter(row["fm1_status"] for row in pairs)
    summary_rows = [
        {"measure": "medical_metric_count", "value": len(medical), "interpretation": "T1-T4 medical-data quantities"},
        {"measure": "analysis_measure_count", "value": len(boundary), "interpretation": "excluded from medical metric denominator"},
        {"measure": "immediately_executable_descriptive_H1", "value": sum(row["h1_recoverability_status"] == "eligible_descriptive_now" for row in medical), "interpretation": "candidate.tumor_fraction only under current paired truth"},
        {"measure": "H2_pairs_audited", "value": len(pairs), "interpretation": "planning audit, not authorization"},
        {"measure": "H2_pairs_executable_now", "value": 0, "interpretation": "none meet linkage, adequacy and external requirements"},
        {"measure": "study_local_T1_reference_candidates", "value": len(local), "interpretation": "PTEN/ERG/SPOP/AR require provenance registration"},
    ]
    write_delimited(OUT / "fm1_summary.csv", list(summary_rows[0]), summary_rows, ",")
    report = [
        "# FM1 지표 적격성·독립성 감사", "",
        "- 판정: **FM1 registry audit complete; no H2 execution unlocked**",
        f"- 의료 정량지표: {len(medical)}개 (" + ", ".join(f"{key} {tier_counts[key]}" for key in sorted(tier_counts)) + ")",
        f"- 별도 analysis measure: {len(boundary)}개",
        "- 현재 paired truth로 즉시 실행 가능한 descriptive H1: **1개 — candidate.tumor_fraction**",
        "- 현재 실행 가능한 H2: **0개**", "",
        "## 첫 번째 의미 있는 산출물", "",
        "`medical_metric_eligibility.tsv`는 58개 의료 정량지표 전부에 대해 reference 독립성, 측정 준비도, H1 역할, H2 상태와 차단 근거를 부여한다. 단순 목록이 아니라 후속 데이터 수집과 모델 검증의 실행 대상을 결정하는 registry다.", "",
        "## H1 판정 분포", "",
        *[f"- {key}: {value}" for key, value in sorted(h1_counts.items())], "",
        "## H2 사전 감사", "",
        *[f"- {key}: {value}" for key, value in sorted(h2_counts.items())], "",
        "우선 계획 후보는 ISUP grade group–biochemical recurrence이며, linked subject/outcome, 사건 수, 치료 공변량과 외부 recurrence cohort가 확보되기 전에는 분석하지 않는다.",
        "Tumor presence–cancer diagnosis와 PNI presence–PNI diagnosis는 circular pair로 금지한다.",
        "PTEN/ERG/SPOP/AR은 중앙 카탈로그에 없는 study-local T1 reference 후보로 등록했으며 assay provenance 전에는 사용하지 않는다.", "",
        "## Claim boundary", "",
        "FM1은 eligibility와 독립성 감사다. 모델 성능, 질병예측 활용, 임상 타당성 또는 encoder 우월성을 보여주는 결과가 아니다.",
    ]
    (OUT / "FM1_REPORT.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    sources = [*MEDICAL_FILES, ANALYSIS_FILE, PLAN, PROTOCOL]
    config = {
        "schema_version": "fm1-eligibility-1.0",
        "seed_reserved": SEED,
        "started_at_utc": started,
        "finished_at_utc": utc_now(),
        "source_hashes": {str(path.relative_to(ROOT)): sha256_file(path) for path in sources},
        "counts": {"medical": len(medical), "analysis": len(boundary), "h2_pairs": len(pairs), "local_references": len(local)},
        "tier_counts": dict(sorted(tier_counts.items())),
        "h1_status_counts": dict(sorted(h1_counts.items())),
        "h2_status_counts": dict(sorted(h2_counts.items())),
        "output_hashes_excluding_run_config": {
            path.name: sha256_file(path) for path in sorted(OUT.iterdir()) if path.is_file() and path.name != "run_config.json"
        },
    }
    (OUT / "run_config.json").write_text(json.dumps(config, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(config["counts"], ensure_ascii=False, sort_keys=True))


if __name__ == "__main__":
    main()
