"""Quantitative metrics for the VLM pathology research workspace."""

from .catalog import (
    ALL_REGISTERED_MEASURES,
    ANALYSIS_CATALOG,
    CATALOG,
    MEASURE_CATALOG,
    MEDICAL_CATALOG,
    MedicalMetricDefinition,
    MetricDefinition,
    analysis_catalog,
    catalog,
    export_analysis_catalog,
    export_catalog,
    export_measure_catalog,
    get_measure,
    get_metric,
    measure_catalog,
)
from .core import (
    BinaryDiscrimination,
    IntervalSummary,
    benjamini_hochberg,
    binary_discrimination,
    capture_fraction,
    cohen_kappa,
    dice_coefficient,
    exact_binomial_ci,
    frozen_combined_score,
    paired_effect,
    percentile_interval,
    raw_agreement,
    review_coverage,
    safe_fraction,
    spearman_rho,
    student_t_interval,
    top_k_precision,
)
from .survey import (
    COMBINATIONS,
    DISEASE_USES,
    REFERENCES,
    DiseaseMetricUse,
    MetricCombination,
    MetricDiseaseScope,
    SurveyReference,
    all_metric_disease_scopes,
    disease_uses,
    diseases,
    export_survey,
    metric_disease_scope,
    metric_uses,
    recommend_combinations,
    survey_references,
)

__all__ = [
    "ALL_REGISTERED_MEASURES", "ANALYSIS_CATALOG", "CATALOG", "COMBINATIONS",
    "DISEASE_USES", "MEASURE_CATALOG", "MEDICAL_CATALOG", "REFERENCES",
    "BinaryDiscrimination", "DiseaseMetricUse", "IntervalSummary", "MetricCombination",
    "MedicalMetricDefinition", "MetricDefinition", "MetricDiseaseScope", "SurveyReference",
    "all_metric_disease_scopes",
    "analysis_catalog", "benjamini_hochberg", "binary_discrimination", "capture_fraction",
    "catalog", "cohen_kappa", "dice_coefficient", "exact_binomial_ci",
    "export_analysis_catalog", "export_catalog", "export_measure_catalog",
    "frozen_combined_score", "get_metric", "paired_effect", "percentile_interval",
    "raw_agreement", "review_coverage", "safe_fraction", "spearman_rho",
    "disease_uses", "diseases", "export_survey", "metric_disease_scope", "metric_uses",
    "get_measure", "measure_catalog", "recommend_combinations", "student_t_interval",
    "survey_references", "top_k_precision",
]

__version__ = "0.3.0"
