"""CONCH (pathology-specific vision-language model, MahmoodLab, Nature Medicine 2024) version
of pilot_clip_similarity_feature.py. That earlier pilot used generic openai/clip-vit-large-
patch14-336 (web image-text pairs, not pathology-tuned) and its docstring flagged a
pathology-specific CLIP as "the natural next thing to try if this comes back flat" -- this
is that follow-up.

Same method as the CLIP pilot: no LLM verdict, no text generation. Compute cosine similarity
of each crop's image embedding against two fixed text prompts (benign-basal-ring vs
malignant-basal-loss), take score = sim_malignant - sim_benign, then compare the score
distribution between the suspect and benign_ref groups produced by
v2_gland_lumen_analysis.py -- across all 4 GNUH slides this time (the CLIP pilot only
covered 1034538). Crops were regenerated after the shape-filter fix in common.py
(find_gland_candidates, min_lumen_thickness) so dab_ring values here match the current,
post-fix pipeline output, not the stale ones baked into the CLIP pilot's CANDIDATES list.

Run with the CONCH-only venv:
    resources/projects/prostate_biomarker_validation/model_workspace/.venv-conch/bin/python resources/projects/prostate_biomarker_validation/model_workspace/pilot_conch_similarity_feature.py
"""
import os
import torch
import torch.nn.functional as F
from PIL import Image
from scipy import stats
from conch.open_clip_custom import create_model_from_pretrained, get_tokenizer, tokenize

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CROPS_DIR = os.path.join(REPO_ROOT, "song-datasets", "_previews", "gland_candidates")
MODEL_CFG = "conch_ViT-B-16"
HF_HUB_ID = "hf_hub:MahmoodLab/conch"

# dab_ring values as regenerated by v2_gland_lumen_analysis.py AFTER the shape-filter fix
# (see common.py find_gland_candidates min_lumen_thickness). Re-run that script first if
# these ever drift from its printed output.
SLIDES = {
    "1034532": [("suspect_1", 0.0173, "suspect"), ("suspect_2", 0.0231, "suspect"), ("suspect_3", 0.0639, "suspect"),
                ("benign_ref_1", 0.1539, "benign"), ("benign_ref_2", 0.1416, "benign"), ("benign_ref_3", 0.1382, "benign")],
    "1034536": [("suspect_1", 0.0357, "suspect"), ("suspect_2", 0.0368, "suspect"), ("suspect_3", 0.0369, "suspect"),
                ("benign_ref_1", 0.0514, "benign"), ("benign_ref_2", 0.0500, "benign"), ("benign_ref_3", 0.0495, "benign")],
    "1034538": [("suspect_1", 0.0213, "suspect"), ("suspect_2", 0.0248, "suspect"), ("suspect_3", 0.0254, "suspect"),
                ("benign_ref_1", 0.0993, "benign"), ("benign_ref_2", 0.0890, "benign"), ("benign_ref_3", 0.0888, "benign")],
    "1034554": [("suspect_1", 0.0163, "suspect"), ("suspect_2", 0.0181, "suspect"), ("suspect_3", 0.0233, "suspect"),
                ("benign_ref_1", 0.0647, "benign"), ("benign_ref_2", 0.0611, "benign"), ("benign_ref_3", 0.0604, "benign")],
}

TEXT_BENIGN = ("a histopathology image of a prostate gland with an intact, continuous brown "
               "basal cell layer ring, benign")
TEXT_MALIGNANT = ("a histopathology image of a prostate gland with loss of the basal cell "
                  "layer, no ring, suspicious for carcinoma")


def main():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, preprocess = create_model_from_pretrained(MODEL_CFG, HF_HUB_ID)
    model = model.to(device).eval()
    tokenizer = get_tokenizer()

    with torch.inference_mode():
        text_tokens = tokenize(texts=[TEXT_BENIGN, TEXT_MALIGNANT], tokenizer=tokenizer).to(device)
        text_features = model.encode_text(text_tokens)
        text_features = F.normalize(text_features, dim=-1)

    results = []
    for slide, candidates in SLIDES.items():
        for tag, dab_ring, label in candidates:
            path = os.path.join(CROPS_DIR, f"{slide}_{tag}.png")
            image = preprocess(Image.open(path).convert("RGB")).unsqueeze(0).to(device)
            with torch.inference_mode():
                img_features = model.encode_image(image, proj_contrast=True, normalize=True)
                sims = (img_features @ text_features.T).squeeze(0).cpu().tolist()
            sim_benign, sim_malignant = sims
            score = sim_malignant - sim_benign
            results.append(dict(slide=slide, tag=tag, dab_ring=dab_ring, label=label,
                                 sim_benign=sim_benign, sim_malignant=sim_malignant, score=score))
            print(f"{slide} {tag:14s} label={label:7s} dab_ring={dab_ring:.4f}  "
                  f"sim_benign={sim_benign:.4f}  sim_malignant={sim_malignant:.4f}  score={score:+.4f}")

    print(f"\n{'='*80}\nPER-SLIDE SUMMARY\n{'='*80}")
    for slide in SLIDES:
        s = [r["score"] for r in results if r["slide"] == slide and r["label"] == "suspect"]
        b = [r["score"] for r in results if r["slide"] == slide and r["label"] == "benign"]
        u, p = stats.mannwhitneyu(s, b, alternative="two-sided")
        print(f"{slide}: suspect mean={sum(s)/3:+.4f}  benign_ref mean={sum(b)/3:+.4f}  "
              f"diff={sum(s)/3 - sum(b)/3:+.4f}  Mann-Whitney p={p:.4g}")

    print(f"\n{'='*80}\nPOOLED SUMMARY (n=24 crops, 4 slides x 6)\n{'='*80}")
    suspect_scores = [r["score"] for r in results if r["label"] == "suspect"]
    benign_scores = [r["score"] for r in results if r["label"] == "benign"]
    print(f"suspect mean={sum(suspect_scores)/len(suspect_scores):+.4f}  "
          f"benign_ref mean={sum(benign_scores)/len(benign_scores):+.4f}")
    u, p = stats.mannwhitneyu(suspect_scores, benign_scores, alternative="two-sided")
    rho, rp = stats.spearmanr([r["dab_ring"] for r in results], [r["score"] for r in results])
    print(f"Mann-Whitney U p={p:.4g} (n=12 vs 12, pooled across slides -- still small, read qualitatively)")
    print(f"Spearman(dab_ring, conch_score) = {rho:+.3f} p={rp:.4g} "
          f"(expect negative: higher dab_ring=more benign, lower malignant-score)")

    print(f"\nNOTE: dab_ring is NOT slide-comparable (see report.tex \\S4.2 tab:dabvalues) -- "
          f"the pooled Spearman correlation mixes 4 different absolute scales, included here "
          f"only as a rough directional check, not a validated statistic.")


if __name__ == "__main__":
    main()
